### ISSUE TITLE
 little readme mistake

### ISSUE THREAD

**Issue by LucasBublitz** [ERROPiX/ESP32_AnalogWrite#1]
Hi,
thanks for the great pojekt.
There is a little mistake in the readme. Under the point PWM Frequency you mixt the function names analogWriteFrequency and analogWriteResolution:)

Lucas

**Comment by ERROPiX** [comment]
@LucasBublitz I fixed that, thank you for the report

**Comment by ERROPiX** [comment]
Hi,

Sorry about this issue, it happens due to some conflicts with vc addons
that try to render shortcodes in the backend, it's fixed in the development
version (attached to this email) that I am going to upload shortly

Thanks


 wp-brain-dev.zip
<https://drive.google.com/file/d/1H6gR3RN052An7aMUr4zaAn7vKqOQlPkw/view?usp=drive_web>
